backend:
  name: git-gateway
  branch: main

publish_mode: editorial_workflow
media_folder: "assets/uploads"
public_folder: "/assets/uploads"

site_url: "https://etdigitalcard.netlify.app"
display_url: "https://etdigitalcard.netlify.app"
logo_url: "https://etdigitalcard.netlify.app/assets/logo.png"

collections:
  - name: "site"
    label: "Site Settings"
    files:
      - label: "Main Content"
        name: "site"
        file: "content/site.json"
        fields:
          - { label: "Full Name", name: "name", widget: "string" }
          - { label: "Job Title", name: "title", widget: "string" }
          - { label: "Organization", name: "org", widget: "string" }
          - { label: "Profile Image", name: "profile", widget: "image" }
          - { label: "Logo", name: "logo", widget: "image" }

  - name: "links"
    label: "Social Links"
    folder: "content/links"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "URL", name: "url", widget: "string" }
      - { label: "Icon", name: "icon", widget: "string", default: "🔗" }
      - { label: "Visible", name: "visible", widget: "boolean", default: true }

  - name: "about"
    label: "About Page"
    files:
      - label: "About"
        name: "about"
        file: "content/about.json"
        fields:
          - { label: "Heading", name: "heading", widget: "string" }
          - { label: "Body", name: "body", widget: "text" }
          - label: "Gallery"
            name: "gallery"
            widget: "list"
            field: { label: "Image", name: "image", widget: "image" }
